name: Prikorm
options:
  bundleIdPrefix: com.prikorm
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  Prikorm:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prikorm.app
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Pudding"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: A89ST3SFXS
  PrikormTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Prikorm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prikorm.tests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
schemes:
  Prikorm:
    build:
      targets:
        Prikorm: all
    test:
      targets:
        - PrikormTests
